version: 2

jobs:
    build:
        working_directory: ~/guesswork
        docker:
            - image: circleci/node:8.9.4
        environment:
              CHROMIUM_BIN: "~/guesswork/chrome-linux/chrome"
        steps:
            - checkout
            - run:
                name: Set permissions
                command: sudo chown -R circleci /usr/local/lib/node_modules && sudo chown -R circleci /usr/local/bin
            - run:
                name: Install Chromium 65
                command: wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F540276%2Fchrome-linux.zip?alt=media && unzip Linux_x64%2F540276%2Fchrome-linux.zip?alt=media
            - run:
                name: Install Chromium dependencies
                command: sudo apt-get update && sudo apt-get install libxcomposite1 libxcursor1 libxi6 libxtst6 libnss3 libcups2
            - run:
                name: test
                command: ~/guesswork/chrome-linux/chrome
            - run:
                name: Install Firefox 59
                command: wget https://ftp.mozilla.org/pub/firefox/releases/59.0.2/linux-x86_64/en-US/firefox-59.0.2.tar.bz2 && tar -xjf firefox-59.0.2.tar.bz2
            - run:
                name: Install Firefox dependencies
                command: sudo apt-get update && sudo apt-get install libgtk-3-dev
            - run: npm install
            - run: PATH=$PATH:~/guesswork/firefox && npm test
