version: 2

jobs:
    build:
        working_directory: ~/redux-store-element
        docker:
            - image: circleci/node:latest-browsers
        environment:
              CHROMIUM_BIN: "/usr/bin/google-chrome"
        steps:
            - checkout
            - run:
                name: Set permissions
                command: sudo chown -R circleci /usr/local/lib/node_modules && sudo chown -R circleci /usr/local/bin
            - run: npm install
            - run: npm test
